const runtime = {
  clientId: null,
  localNickname: null,
  peerId: null,
  peerNickname: 'OPPONENT',
  coordinatorId: null,
  state: null,
  prepared: false,
  started: false,
  uiLocked: true,
  waitEnemyVisible: false,
  pendingActionId: null,
  actionStartedAt: 0,
  actionTimeoutId: null,
  revealTimerId: null,
  introTimerId: null,
  firstUserAniGameId: null,
  firstUserAniCompletedGameId: null,
  firstUserAniTimerIds: [],
  firstUserAniResizeHandler: null,
  helloRetryId: null,
  helloRetryCount: 0,
  resizeRaf: 0,
  resultMarkedGameId: null,
  handlers: {
    boardClick: null,
    leaveFinishedGame: null,
  },
  elements: {
    gameScene: null,
    intro: null,
    introTitle: null,
    introText: null,
    enemyBlock: null,
    enemyList: null,
    enemyIcon: null,
    pictureBoard: null,
    board: null,
    boardButtons: [],
    playerBlock: null,
    playerList: null,
    playerIcon: null,
    result: null,
    resultTitle: null,
  },
};

export default runtime;
