server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location = / {
        try_files /index.html =404;
    }

    location = /selectGame {
        try_files /views/selectGame.html =404;
    }

    location = /game/taptap {
        try_files /views/game/taptap.html =404;
    }

    location = /game/indianPocker {
        try_files /views/game/indianPocker.html =404;
    }

    location = /game/blackAndWhite1 {
        try_files /views/game/blackAndWhite1.html =404;
    }

    location = /game/findTheSamePicture {
        try_files /views/game/findTheSamePicture.html =404;
    }

    location ~* \.(js|css|svg|png|jpg|jpeg|gif|webp|woff|woff2|ttf|otf)$ {
        try_files $uri =404;

        expires 7d;
        add_header Cache-Control "public";
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
