import bcrypt from "bcryptjs";

// export let bcrypt = bcrypt;
export let activeCard = {};
export let pcActiveEl;
export let pcOffsetLeft = 0;
export let pcOffsetTop = 0;
export let mtX = 0;
export let mtY = 0;
export let mmX = 0;
export let mmY = 0;
export let mTargetIdx = 0;
export let pcMoveX = 0;
export let pcMoveY = 0;
export let selectX = 0;
export let selectY = 0;
export let cardLen = 20;
export let comnArray = [];
// let allInintrtval = 2000;
export let allInintrtval = 1000;
